@startuml
start
:Реми дергает за волосы;
:Сигнал передается Лингвини;
:Лингвини двигает рукой;
if (Какой сигнал?) then (налево)
  :Сдвинуть руку с овощем;
else (направо)
  :Сдвинуть руку к плите;
endif
:Нарезка овощей;
:Добавление ингредиентов;
:Блюдо готово;
stop
@enduml
